import { ArrowDown, ArrowUp, ChartLineUp, Star } from "@phosphor-icons/react/dist/ssr";

import { ensureAppUser } from "@/lib/auth/app-user";
import { requireUserSession } from "@/lib/auth/server";
import { resolveParentChild } from "@/lib/parent/page-data";
import { ParentEmptyState, ParentShell } from "@/components/parent/parent-shell";

export const dynamic = "force-dynamic";

export default async function ParentProgressPage({ searchParams }: { searchParams: Promise<{ studentId?: string }> }) {
  const session = await requireUserSession();
  await ensureAppUser({ id: session.user.id, email: session.user.email, name: session.user.name });
  const { studentId, data } = await resolveParentChild(session.user.id, (await searchParams).studentId);
  if (!studentId || !data) return <ParentShell active="Tiến bộ" childName="Phù Đổng" className="Cổng phụ huynh" studentId="none"><ParentEmptyState /></ParentShell>;
  const positive = data.scores.filter((item) => Number(item.spendableDelta) > 0).reduce((total, item) => total + Number(item.spendableDelta), 0);
  const improvements = data.scores.filter((item) => Number(item.spendableDelta) < 0).reduce((total, item) => total + Math.abs(Number(item.spendableDelta)), 0);
  return <ParentShell active="Tiến bộ" childName={data.child.fullName} className={data.child.className} studentId={studentId}><div className="mb-6"><p className="font-heading text-sm font-bold uppercase tracking-[0.14em] text-[var(--tertiary)]">Theo dõi nhẹ nhàng</p><h1 className="mt-2 font-heading text-4xl font-bold text-[var(--primary)]">Tiến bộ của con</h1><p className="mt-2 font-body text-sm leading-6 text-[var(--on-surface-variant)]">Nhìn vào hành trình của con, không so sánh với bạn khác.</p></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[var(--surface-lowest)] p-5 soft-shadow"><Star size={22} className="text-[var(--secondary)]" weight="fill" /><p className="mt-4 font-body text-sm text-[var(--on-surface-variant)]">Điểm tích cực</p><p className="mt-1 font-heading text-3xl font-bold text-[var(--primary)]">{positive}</p></div><div className="rounded-2xl bg-[var(--surface-lowest)] p-5 soft-shadow"><ArrowDown size={22} className="text-[var(--needs-improvement)]" /><p className="mt-4 font-body text-sm text-[var(--on-surface-variant)]">Điều cần cải thiện</p><p className="mt-1 font-heading text-3xl font-bold text-[var(--primary)]">{improvements}</p></div><div className="rounded-2xl bg-[var(--surface-lowest)] p-5 soft-shadow"><ChartLineUp size={22} className="text-[var(--positive)]" /><p className="mt-4 font-body text-sm text-[var(--on-surface-variant)]">Tổng điểm</p><p className="mt-1 font-heading text-3xl font-bold text-[var(--primary)]">{data.child.lifetimeScore}</p></div></div><section className="mt-6 rounded-[2rem] bg-[var(--surface-lowest)] p-6 soft-shadow"><h2 className="font-heading text-2xl font-bold text-[var(--on-surface)]">Dòng thời gian hoạt động</h2><div className="mt-5 space-y-3">{data.scores.map((item) => <div key={item.id} className="flex gap-3 rounded-2xl bg-[var(--surface-low)] p-4"><span className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${Number(item.spendableDelta) >= 0 ? "bg-[var(--positive-soft)] text-[var(--positive)]" : "bg-[var(--needs-improvement-soft)] text-[var(--needs-improvement)]"}`}>{Number(item.spendableDelta) >= 0 ? <ArrowUp size={16} /> : <ArrowDown size={16} />}</span><div className="min-w-0 flex-1"><p className="font-body text-sm text-[var(--on-surface)]">{item.reason}</p><p className="mt-1 font-body text-xs text-[var(--on-surface-variant)]">{new Date(item.occurredAt).toLocaleDateString("vi-VN")} · {item.transactionType}</p></div><span className="font-heading text-sm font-bold text-[var(--primary)]">{Number(item.spendableDelta) > 0 ? "+" : ""}{item.spendableDelta}</span></div>)}{data.scores.length === 0 ? <p className="font-body text-sm text-[var(--on-surface-variant)]">Chưa có dữ liệu tiến bộ.</p> : null}</div></section></ParentShell>;
}
